# Generated by Django 4.1 on 2023-11-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polymorph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVS',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polymorph.service')),
                ('session', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('polymorph.service',),
        ),
    ]
