# Generated by Django 4.1 on 2023-11-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ct', '0002_alter_order_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'pk__in': [13, 14, 15]}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
